apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - chaos-testing
    labelSelectors:
      'app': 'apache'
  delay:
    latency: "100ms"
    correlation: "25"
    jitter: "10ms"
  duration: "15s"
  scheduler:
    cron: "@every 30s"